# Generated by Django 3.1.2 on 2020-10-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='second',
            new_name='last',
        ),
    ]
